-- ⚠️ This script will DROP (delete) and recreate the listed tables + view in `public`.
-- Run only if you really want to replace the existing schema objects.

BEGIN;

-- Drop view first (depends on tables)
DROP VIEW IF EXISTS public.questions_with_media;

-- Drop tables (CASCADE to remove dependent constraints/indexes cleanly)
DROP TABLE IF EXISTS public.answers CASCADE;
DROP TABLE IF EXISTS public.cloze_templates CASCADE;
DROP TABLE IF EXISTS public.content_admins CASCADE;
DROP TABLE IF EXISTS public.languages CASCADE;
DROP TABLE IF EXISTS public.lesson_attempts CASCADE;
DROP TABLE IF EXISTS public.lessons CASCADE;
DROP TABLE IF EXISTS public.media CASCADE;
DROP TABLE IF EXISTS public.module_completion CASCADE;
DROP TABLE IF EXISTS public.onboarding_answers CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.sentence_tokens CASCADE;
DROP TABLE IF EXISTS public.sentence_translations CASCADE;
DROP TABLE IF EXISTS public.sentences CASCADE;
DROP TABLE IF EXISTS public.user_progress CASCADE;
DROP TABLE IF EXISTS public.user_responses CASCADE;
DROP TABLE IF EXISTS public.words CASCADE;

-- Recreate tables (in dependency order)

CREATE TABLE public.languages (
  code text NOT NULL,
  name text NOT NULL,
  CONSTRAINT languages_pkey PRIMARY KEY (code)
);

CREATE TABLE public.lessons (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  description text,
  cefr_level text,
  title text,
  display_order integer DEFAULT 0,
  CONSTRAINT lessons_pkey PRIMARY KEY (id)
);

CREATE TABLE public.media (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  type text NOT NULL,
  url text NOT NULL,
  description text,
  CONSTRAINT media_pkey PRIMARY KEY (id)
);

CREATE TABLE public.sentences (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  language_code text NOT NULL,
  text text NOT NULL,
  source text,
  difficulty integer DEFAULT 1,
  audio_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sentences_pkey PRIMARY KEY (id),
  CONSTRAINT sentences_language_code_fkey FOREIGN KEY (language_code) REFERENCES public.languages(code)
);

CREATE TABLE public.words (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  language_code text NOT NULL,
  text text NOT NULL,
  lemma text,
  pos text,
  ipa text,
  audio_url text,
  frequency integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT words_pkey PRIMARY KEY (id),
  CONSTRAINT words_language_code_fkey FOREIGN KEY (language_code) REFERENCES public.languages(code)
);

CREATE TABLE public.questions (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  lesson_id integer,
  media_id integer,
  type text NOT NULL,
  question_text text,
  prompt text,
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT questions_media_id_fkey FOREIGN KEY (media_id) REFERENCES public.media(id)
);

CREATE TABLE public.answers (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  question_id integer,
  answer_text text NOT NULL,
  is_correct boolean NOT NULL,
  CONSTRAINT answers_pkey PRIMARY KEY (id),
  CONSTRAINT answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);

CREATE TABLE public.cloze_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sentence_id bigint NOT NULL,
  blank_token_indices integer[] NOT NULL,
  distractors text[] NOT NULL DEFAULT '{}'::text[],
  prompt text,
  explanation text,
  level integer DEFAULT 1,
  enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cloze_templates_pkey PRIMARY KEY (id),
  CONSTRAINT cloze_templates_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id),
  CONSTRAINT cloze_templates_blank_token_indices_check CHECK (array_length(blank_token_indices, 1) > 0),
  CONSTRAINT cloze_templates_distractors_check CHECK (array_length(distractors, 1) >= 0)
);

CREATE TABLE public.sentence_translations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sentence_id bigint NOT NULL,
  target_language_code text NOT NULL,
  text text NOT NULL,
  literal_gloss text,
  is_machine boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sentence_translations_pkey PRIMARY KEY (id),
  CONSTRAINT sentence_translations_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id),
  CONSTRAINT sentence_translations_target_language_code_fkey FOREIGN KEY (target_language_code) REFERENCES public.languages(code)
);

CREATE TABLE public.sentence_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sentence_id bigint NOT NULL,
  token_index integer NOT NULL,
  start_pos integer,
  end_pos integer,
  text text NOT NULL,
  lemma text,
  pos text,
  word_id bigint,
  CONSTRAINT sentence_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT sentence_tokens_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id),
  CONSTRAINT sentence_tokens_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words(id)
);

CREATE TABLE public.content_admins (
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_admins_pkey PRIMARY KEY (user_id),
  CONSTRAINT content_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.onboarding_answers (
  user_id uuid NOT NULL,
  answers jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT onboarding_answers_pkey PRIMARY KEY (user_id),
  CONSTRAINT onboarding_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.module_completion (
  user_id uuid NOT NULL,
  completed text[] NOT NULL DEFAULT '{}'::text[],
  updated_at timestamp with time zone DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  CONSTRAINT module_completion_pkey PRIMARY KEY (user_id),
  CONSTRAINT module_completion_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.lesson_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  course_slug text NOT NULL,
  question_id integer NOT NULL,
  choice text NOT NULL,
  correct boolean NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT lesson_attempts_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);

CREATE INDEX idx_lesson_attempts_question_id ON public.lesson_attempts(question_id);

CREATE TABLE public.user_progress (
  user_id uuid NOT NULL,
  question_id integer NOT NULL,
  easiness numeric,
  interval integer,
  repetitions integer,
  last_review date,
  next_review date,
  CONSTRAINT user_progress_pkey PRIMARY KEY (user_id, question_id),
  CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_progress_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);

CREATE TABLE public.user_responses (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid,
  question_id integer,
  accuracy boolean NOT NULL,
  time_to_respond integer,
  attempts integer,
  error_type text,
  answered_at timestamp with time zone,
  CONSTRAINT user_responses_pkey PRIMARY KEY (id),
  CONSTRAINT user_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);

-- Recreate view
CREATE OR REPLACE VIEW public.questions_with_media AS
SELECT
  q.*,
  m.url AS media_url
FROM public.questions q
LEFT JOIN public.media m ON q.media_id = m.id;

COMMIT;
